### ISSUE TITLE
Better haneling of action='store_true'

### ISSUE THREAD

**Issue by guysoft** [nhoffman/argparse-bash#10]
If action='store_true' is set, then the variable starts ``True`` or ``False`` strings, might be a better way to do this.

**Comment by nhoffman** [comment]
@guysoft - thanks for the suggestion. Any thoughts on https://github.com/nhoffman/argparse-bash/commit/f470c6ec1644443f46eab94cbdd744502b1724ac ?

**Comment by nhoffman** [comment]
closed by 6352c3b

**Comment by guysoft** [comment]
Great, tested and works in here:
https://github.com/guysoft/CustomPiOS/blob/CustomPiOS/src/make_custom_pi_os
