### ISSUE TITLE
Run the example.sh

### ISSUE THREAD

**Issue by efratushava** [nhoffman/argparse-bash#12]
Hi

I'm trying to run the example.sh script: bash /home/alu/ekushele/script/bash/conf.sh
I'm getting an error: 
/home/alu/ekushele/script/bash/conf.sh: line 28: warning: here-document at line 4 delimited by end-of-file (wanted `EOF')
  File "/tmp/tmp.hl53hz9h93", line 25
    echo required infile: ""
                ^
SyntaxError: invalid syntax
: numeric argument requiredash/conf.sh: line 4: exit: 1

What can I do?

**Comment by nhoffman** [comment]
Can you please provide the tar archive generated below?

```
tar -cf argparse-bash-gh12.tar /home/alu/ekushele/script/bash/{conf.sh,argparse.bash}
```

Also, what is your OS and version of bash and python?

**Comment by efratushava** [comment]
OS-CentOS6, 
python-Python 2.7.15 but I can use Python 3.3.3
bash: GNU bash, version 4.1.2(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

When running 
tar -cf argparse-bash-gh12.tar /home/alu/ekushele/script/bash/{conf.sh,argparse.bash}
I get: 

tar: Removing leading `/' from member names
I can't upload the archive, since this github doesn't support uploading of tar files

**Comment by nhoffman** [comment]
I suppose I was trying to be a bit too clever asking for a tarball like that - I basically just wanted to confirm that argparse.bash was in the same directory (it is, based on tar's message), and of course to be able to test the file with no risk of modifying characters by pasting it into a comment. Will github let you attach `conf.sh`? If not, please just paste it into a comment or upload it to a gist.

**Comment by efratushava** [comment]
I just copied the example script:
#!/bin/bash

ARGPARSE_DESCRIPTION="Sample script description"      # this is optional
source $(dirname $0)/argparse.bash || exit 1
argparse "$@" <<EOF || exit 1
parser.add_argument('infile')
parser.add_argument('outfile')
parser.add_argument('-a', '--the-answer', default=42, type=int,
                    help='Pick a number [default %(default)s]')
parser.add_argument('-d', '--do-the-thing', action='store_true',
                    default=False, help='store a boolean [default %(default)s]')
parser.add_argument('-m', '--multiple', nargs='+',
                    help='multiple values allowed')
EOF

echo required infile: "$INFILE"
echo required outfile: "$OUTFILE"
echo the answer: "$THE_ANSWER"
echo -n do the thing?
if [[ $DO_THE_THING ]]; then
    echo " yes, do it"
else
    echo " no, do not do it"
fi
echo -n "arg with multiple values: "
for a in "${MULTIPLE[@]}"; do
    echo -n "[$a] "
done
echo

**Comment by nhoffman** [comment]
Thanks. I'm afraid that I can't reproduce your error after pasting the lines above directly into a file (python 2.7.14, GNU bash version 3.2.57, masOS 10.13.6), and I don't have any way to test on an equivalent system to yours. The only thing that I can suggest is to clone the repo and try the example there to rule out any possible whitespace or other issues caused by copy-pasting:

```
git clone https://github.com/nhoffman/argparse-bash.git
bash argparse-bash/example.sh foo bar 
```

Otherwise, I'm afraid I don't have any ideas. I can leave this issue open in case anyone else can reproduce the problem and suggest a solution.

**Comment by efratushava** [comment]
Thank you!

I cloned the repo, and ran:
[ekushele@alu01 bash]$ bash argparse-bash/example.sh foo bar

Is that the ouput I need to get?
#!/bin/bash

source $(dirname $0)/argparse.bash || exit 1
argparse "$@" <<EOF || exit 1
parser.add_argument('infile')
parser.add_argument('-o', '--outfile')

EOF

echo "INFILE: ${INFILE}"
echo "OUTFILE: ${OUTFILE}"
required infile: foo
required outfile: bar
the answer: 42
do the thing? no, do not do it

**Comment by nhoffman** [comment]
Interesting - the lines starting with 'required infile: foo' were expected; the lines before were not (executing argparse.bash is supposed to print the example script that you see above). I updated the condition that determines whether these lines are printed to be a little bit more explicit. The expected output looks like this:

```
% bash argparse-bash/example.sh foo bar
required infile: foo
required outfile: bar
the answer: 42
do the thing? no, do not do it
arg with multiple values: []
```

What do you see if you pull (``cd argparse-bash && git pull origin master``) and try again? 

In any case, there are no errors, or at least we don't see the error you reported initially. At this point, if you are still interested in using this, I'd suggest adapting the example.sh script from the repo and developing it iteratively. If the example script continues to print, you can always delete the lines in argparse.bash after the comment `# print a script template when this script is executed`. Good luck!

**Comment by efratushava** [comment]
Now I get:
$ bash example.sh  foo bar
required infile: foo
required outfile: bar
the answer: 42
do the thing? no, do not do it
arg with multiple values: []

Is that fine?

**Comment by nhoffman** [comment]
This is the expected output for the example script. Looks like it's working as expected. Feel free to re-open if you run into any other unexplained errors.
