### ISSUE TITLE
Using an 'int' argument of 0 is broken

### ISSUE THREAD

**Issue by alapidas** [nhoffman/argparse-bash#3]
Due to 0 being falsy, this code fails to parse an int argument of 0

https://github.com/nhoffman/argparse-bash/blob/master/argparse.bash#L39

```
for arg in [a for a in dir(args) if not a.startswith('_')]:
    print('{}="{}";'.format(arg.upper(), getattr(args, arg) or ''))
```

**Comment by nhoffman** [comment]
Fixed by fea2a01 - thanks @alapidas!
