### ISSUE TITLE
Xonsh might be the answer

### ISSUE THREAD

**Issue by certik** [nhoffman/argparse-bash#7]
> The proper thing to do would be to abandon *sh altogether, and instead use a scripting language with a proper library for defining a command line interface. Can anyone think of one?

I think that Xonsh (http://xon.sh/) might be able to do that.

**Comment by nhoffman** [comment]
Thanks for the suggestion! I'll have to check it out. The answer I had in mind for my (admittedly rhetorical) question was of course Python, but the more the merrier!

**Comment by certik** [comment]
I think Xonsh is a superset of Python.
